### PR TITLE
main: Fix typo, tweak command line argument descriptions

### PR DESCRIPTION
**Pull request by cgwalters**
I saw a typo `Custon`, and while here did a quick pass and
cleaned a few other things up a bit.

### CODE REVIEW

**Comment by jlebon** [comment]
LGTM.

**Comment by cgwalters** [comment]
@alexlarsson @giuseppe I propose adding @jlebon to the list of approved reviewers for bubblewrap.  Any objections?

**Comment by giuseppe** [comment]
no objections from me

@rh-atomic-bot r+ 7bd7cfc

**Comment by cgwalters** [comment]
Oh, the current list is:

https://github.com/orgs/projectatomic/teams/bubblewrap-team/members

So let's add both giuseppe and jlebon?

@rh-atomic-bot delegate=jlebon

**Comment by jlebon** [comment]
@rh-atomic-bot r+ 7bd7cfc

**Pull request closed without merging**
