### PR TITLE
Release 0.2.0

### PR DESCRIPTION
**Pull request by cgwalters**
We've got a lot of new features and bugfixes since 0.1.8. Let's cut a new
release before we start landing even more things like the `pivot_root()` PR.

### CODE REVIEW

**Comment by cgwalters** [comment]
```
Alexander Larsson (1):
      Merge pull request #196 from giuseppe/no-reaper

Colin Walters (9):
      demos/shell: Use --die-with-parent
      main: Squash a -Wunused-result error, enable FORTIFY_SOURCE in CI
      tests: Import libtest-core.sh from ostree
      README.md: Delete cat logo picture (not DFSG compliant)
      Retain all caps when invoked by uid 0, work around systemd seccomp filter
      main: Fix typo, tweak command line argument descriptions
      With --dev, add /dev/fd and /dev/core symlinks
      Avoid leaking --args-fd to child process
      Release 0.2.0

Giuseppe Scrivano (8):
      bubblewrap: add --as-pid-1
      bubblewrap: add --cap-add and --cap-drop
      bubblewrap: add option --userns-block-fd
      demos: add demo userns-block-fd.py
      bubblewrap.c: fix typo
      bubblewrap: do not always leave caps in the unprivileged case
      tests: add tests for --cap-add
      README.md: add bwrap-oci to the list of users

Jonathan Lebon (1):
      ci: rename files to new name and bump to f26

Marcos Paulo de Souza (3):
      bubblewrap: Remove not needed MS_MGC_VAL mount flag
      bubblewrap.c: Fix typo secomp -> seccomp in drop_all_caps
      acquire_privs: Cosmetic change to reduce indentation

Philip Withnall (4):
      bubblewrap: Improve const-correctness of argv handling
      bubblewrap: Fix a minor memory leak in --args handling
      bubblewrap: Close FDs on exiting PID 1
      bubblewrap: Add various assertions on SetupOp handling

Simon McVittie (10):
      Distribute test helper library
      tests: Don't write to predictable filenames in /tmp
      tests: Improve diagnostics if non-root caps test fails
      tests: Send diagnostics to stderr
      tests: Interpret stdout as TAP syntax
      tests: Produce finer-grained TAP output
      tests: Ensure non-root users have access to libcap tools
      Partially revert "bubblewrap: Fix a minor memory leak in --args handling"
      tests: Add basic test coverage for --args
      tests: Fix a race condition between attempts to lock a file

Tristan Cacqueray (1):
      bubblewrap: check for max_user_namespaces == 0

Vasya Novikov (1):
      add --unshare-all completion

```

**Comment by cgwalters** [comment]
Any objections from anyone?

**Comment by smcv** [comment]
A release seems good to have, but I'll smoke-test with Flatpak before saying yes...

**Comment by smcv** [comment]
27eb690 seems fine with Flatpak.

**Comment by cgwalters** [comment]
@rh-atomic-bot delegate=smcv

**Comment by smcv** [comment]
@rh-atomic-bot r+ 7c0ed5b

@cgwalters please note that the shortlog you pasted above is outdated: #234 and #235 were merged since the version we tested. They look harmless, so it would be good to have them in 0.2.0.

**Comment by cgwalters** [comment]
Yep, updated the shortlog for the tag.  Thanks!  https://github.com/projectatomic/bubblewrap/releases/tag/v0.2.0

**Pull request closed without merging**
