### PR TITLE
Post-release version bump to 0.3.1

### PR DESCRIPTION
**Pull request by alexlarsson**
This is useful because you can then test for new features.

### CODE REVIEW

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 28d1d95

**Comment by hasufell** [comment]
There is no tag yet?

**Comment by smcv** [comment]
There won't be a tag until 0.3.1 is actually released, which has not yet happened. git master is currently somewhere between 0.3.0 and 0.3.1.

**Comment by TingPing** [comment]
A new tag would be very valuable, webkitgtk master will soon depend upon this.

**Pull request closed without merging**
