### PR TITLE
[merged] Convert tabs to spaces

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by cgwalters** [comment]
Since we use GNU style we should not use tabs, but it looks like they got in anyways.  If I run `M-x untabify` in Emacs I get a larger diff.

I'd say let's do one big patch to untabify everything now.

**Comment by mrunalp** [comment]
@cgwalters Sounds, good. I'll update the PR. I just noticed this one while scrolling through the code.

**Comment by mrunalp** [comment]
Pushed updated commit.

**Comment by cgwalters** [comment]
Let's do it in all of the `.c` and `.h` files too?

**Comment by alexlarsson** [comment]
I added an uncruftify config to xdg-app, which is mostly ok, and as bubblewrap has the same style maybe we can reuse it:
https://cgit.freedesktop.org/xdg-app/xdg-app/tree/uncrustify.cfg

**Comment by mrunalp** [comment]
Pushed untabify changes on all *.c and *.h files.

**Comment by mrunalp** [comment]
@alexlarsson That looks good! We should probably check for indent/style issues in pre-commit tests if possible.

**Comment by cgwalters** [comment]
Never heard of uncruftify, looks sane though.  I am actively working on PR testing for builds, but it won't run `make check` yet.

@cgwalters-bot r+ e33d63a

**Pull request closed without merging**
