### PR TITLE
Minor fixes from https://github.com/projectatomic/bubblewrap/pull/114

### PR DESCRIPTION
**Pull request by alexlarsson**
These are the trivial commits from https://github.com/projectatomic/bubblewrap/pull/114

### CODE REVIEW

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 6d6cd09

**Comment by cgwalters** [comment]
@rh-atomic-bot r+  	10bafea

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+ 10bafea

**Comment by alexlarsson** [comment]
@rh-atomic-bot retry

**Comment by alexlarsson** [comment]
Anyone knows whats up with homu?

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
The problem was that Homu was still watching Travis, which was hitting auth failures.  I switched it to watch `Red Hat CI`.

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot force

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot clean

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by alexlarsson** [comment]
Ugh, i accidentally pushed this... Sorry.

**Pull request merged**
