### PR TITLE
[merged] Fix capability list in spec file.

### PR DESCRIPTION
**Pull request by wenottingham**
Indirectly related to https://github.com/projectatomic/bubblewrap/issues/102.

### CODE REVIEW

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 30cc13f

**Comment by cgwalters** [comment]
Though the real fix here I think is [in Fedora](http://pkgs.fedoraproject.org/cgit/rpms/bubblewrap.git/commit/?id=eb745575df695df2e31a29e61f51eab67366931c) and to [build for EPEL](http://koji.fedoraproject.org/koji/buildinfo?buildID=804133)

**Comment by cgwalters** [comment]
https://bodhi.fedoraproject.org/updates/bubblewrap-0.1.2-1.el7

**Comment by wenottingham** [comment]
Thanks - the question of whether you were intending to have this in EPEL was coming up....

**Pull request closed without merging**
