### PR TITLE
[merged] man: Correct namespace user -> mount

### PR DESCRIPTION
**Pull request by cgwalters**
Closes: #141

### CODE REVIEW

**Comment by cgwalters** [comment]
@rh-atomic-bot delegate=valoq

**Comment by valoq** [comment]
Looks fine

**Comment by cgwalters** [comment]
@valoq You can approve this commit by typing: @ rh-atomic-bot r+ 0661fd9
(But with no space between @ and rh-atomic-bot)

**Comment by valoq** [comment]
@cgwalters Thanks
@rh-atomic-bot r+ 0661fd9

**Pull request closed without merging**
